import { AlertTriangle, Info } from "lucide-react";

type FallbackLevel = "crusoe" | "static" | null;

type Props = {
  level: FallbackLevel;
};

const MESSAGES: Record<NonNullable<FallbackLevel>, { icon: React.ReactNode; text: string; bg: string }> = {
  crusoe: {
    icon: <Info className="w-4 h-4 flex-shrink-0 text-blue-500" />,
    text: "Primary AI is busy — your routine was generated by our backup model (Llama 3 on Crusoe Cloud).",
    bg: "bg-blue-50 border-blue-100 text-blue-700",
  },
  static: {
    icon: <AlertTriangle className="w-4 h-4 flex-shrink-0 text-amber-500" />,
    text: "AI models are temporarily unavailable. Your routine is based on our curated skin type templates — still great advice!",
    bg: "bg-amber-50 border-amber-100 text-amber-700",
  },
};

export default function FallbackBanner({ level }: Props) {
  if (!level) return null;

  const { icon, text, bg } = MESSAGES[level];

  return (
    <div className={`flex items-start gap-3 px-4 py-3 rounded-xl border text-xs font-medium ${bg}`}>
      {icon}
      <span>{text}</span>
    </div>
  );
}
