"use client";

import { useEffect, useState } from "react";
import { motion, type Variants } from "framer-motion";
import RoutineStep from "./RoutineStep";
import ProductCard from "./ProductCard";
import { Share2, Download, Check } from "lucide-react";
import type { SkinAnalysisResult } from "@/lib/perfectcorp";
import type { RoutineResult } from "@/lib/fallback-chain";

const SKIN_TYPE_LABELS_TEXT: Record<string, string> = {
  oily: "Oily",
  dry: "Dry",
  combination: "Combination",
  normal: "Normal",
  sensitive: "Sensitive",
};

function buildShareText(skin: SkinAnalysisResult, routine: RoutineResult): string {
  const concerns = skin.concerns.length > 0 ? skin.concerns.join(", ") : "None";
  const morningSteps = routine.morning
    .map((s, i) => `${i + 1}. ${s.name} — ${s.description}`)
    .join("\n");
  const nightSteps = routine.night
    .map((s, i) => `${i + 1}. ${s.name} — ${s.description}`)
    .join("\n");

  return [
    "My SkinMatch AI Skin Report",
    `Skin Type: ${SKIN_TYPE_LABELS_TEXT[skin.skin_type] ?? skin.skin_type} | Tone: ${skin.skin_tone}`,
    `Concerns: ${concerns}`,
    "",
    "Morning Routine:",
    morningSteps,
    "",
    "Night Routine:",
    nightSteps,
    "",
    "Generated by SkinMatch AI",
  ].join("\n");
}

function buildRoutineText(skin: SkinAnalysisResult, routine: RoutineResult): string {
  const concerns = skin.concerns.length > 0 ? skin.concerns.join(", ") : "None detected";
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const formatSteps = (steps: RoutineResult["morning"]) =>
    steps
      .map((s, i) => {
        const lines = [`${i + 1}. ${s.name}`, `   ${s.description}`];
        if (s.tip) lines.push(`   Tip: ${s.tip}`);
        return lines.join("\n");
      })
      .join("\n\n");

  const formatProducts = (products: RoutineResult["products"]) =>
    products
      .map((p) => {
        const searchUrl = `https://www.google.com/search?q=${encodeURIComponent(p.brand + " " + p.name)}`;
        return [`• ${p.name} by ${p.brand} (${p.price_range})`, `  ${p.why}`, `  Search: ${searchUrl}`].join("\n");
      })
      .join("\n\n");

  return [
    "SKINMATCH AI — Your Personalized Skincare Routine",
    `Generated: ${date}`,
    "",
    "YOUR SKIN PROFILE",
    `- Skin Type: ${SKIN_TYPE_LABELS_TEXT[skin.skin_type] ?? skin.skin_type}`,
    `- Skin Tone: ${skin.skin_tone}`,
    `- Concerns: ${concerns}`,
    "",
    "MORNING ROUTINE",
    formatSteps(routine.morning),
    "",
    "NIGHT ROUTINE",
    formatSteps(routine.night),
    ...(routine.products.length > 0
      ? ["", "RECOMMENDED PRODUCTS", formatProducts(routine.products)]
      : []),
    "",
    "---",
    "Generated by SkinMatch AI",
  ].join("\n");
}

const SKIN_TYPE_LABELS: Record<string, string> = SKIN_TYPE_LABELS_TEXT;

const cardVariants: Variants = {
  hidden: { opacity: 0, y: 24 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, delay: i * 0.12 },
  }),
};

export default function SkinReportCard() {
  const [skinData, setSkinData] = useState<SkinAnalysisResult | null>(null);
  const [routineData, setRoutineData] = useState<RoutineResult | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const skin = sessionStorage.getItem("skinData");
    const routine = sessionStorage.getItem("routineData");
    if (skin) setSkinData(JSON.parse(skin));
    if (routine) setRoutineData(JSON.parse(routine));
  }, []);

  function handleShare() {
    if (!skinData || !routineData) return;
    const text = buildShareText(skinData, routineData);
    if (typeof navigator.share === "function") {
      navigator.share({ title: "My SkinMatch AI Report", text, url: window.location.href }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text + "\n\n" + window.location.href).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }).catch(() => {
        alert("Copy this link to share:\n" + window.location.href);
      });
    }
  }

  function handleDownload() {
    if (!skinData || !routineData) return;
    const text = buildRoutineText(skinData, routineData);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "skinmatch-routine.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  if (!skinData || !routineData) {
    return (
      <div className="bg-white rounded-2xl p-8 text-center text-gray-400 shadow-sm">
        No analysis data found.{" "}
        <a href="/analyze" className="text-rose-500 font-medium">
          Start over
        </a>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Skin profile summary */}
      <motion.div
        custom={0}
        variants={cardVariants}
        initial="hidden"
        animate="visible"
        className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100"
      >
        <h2 className="text-lg font-bold text-gray-900 mb-4">Your Skin Profile</h2>
        <div className="grid grid-cols-2 gap-3">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.2, duration: 0.4 }}
            className="bg-rose-50 rounded-xl p-4"
          >
            <p className="text-xs text-rose-400 font-medium mb-1">Skin Type</p>
            <p className="text-base font-bold text-rose-700">
              {SKIN_TYPE_LABELS[skinData.skin_type] ?? skinData.skin_type}
            </p>
          </motion.div>
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.3, duration: 0.4 }}
            className="bg-purple-50 rounded-xl p-4"
          >
            <p className="text-xs text-purple-400 font-medium mb-1">Skin Tone</p>
            <p className="text-base font-bold text-purple-700">{skinData.skin_tone}</p>
          </motion.div>
        </div>
        {skinData.concerns.length > 0 && (
          <div className="mt-3">
            <p className="text-xs text-gray-400 font-medium mb-2">Concerns detected</p>
            <div className="flex flex-wrap gap-2">
              {skinData.concerns.map((c, i) => (
                <motion.span
                  key={c}
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.35 + i * 0.06, duration: 0.3 }}
                  className="text-xs bg-gray-100 text-gray-600 px-3 py-1 rounded-full capitalize"
                >
                  {c}
                </motion.span>
              ))}
            </div>
          </div>
        )}
      </motion.div>

      {/* Morning routine */}
      <motion.div
        custom={1}
        variants={cardVariants}
        initial="hidden"
        animate="visible"
        className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100"
      >
        <h2 className="text-base font-bold text-gray-900 mb-4">☀️ Morning Routine</h2>
        <div className="space-y-3">
          {routineData.morning.map((step, i) => (
            <RoutineStep key={i} step={step} index={i + 1} />
          ))}
        </div>
      </motion.div>

      {/* Night routine */}
      <motion.div
        custom={2}
        variants={cardVariants}
        initial="hidden"
        animate="visible"
        className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100"
      >
        <h2 className="text-base font-bold text-gray-900 mb-4">🌙 Night Routine</h2>
        <div className="space-y-3">
          {routineData.night.map((step, i) => (
            <RoutineStep key={i} step={step} index={i + 1} />
          ))}
        </div>
      </motion.div>

      {/* Product recommendations */}
      {routineData.products.length > 0 && (
        <motion.div
          custom={3}
          variants={cardVariants}
          initial="hidden"
          animate="visible"
          className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100"
        >
          <h2 className="text-base font-bold text-gray-900 mb-4">🛍️ Recommended Products</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {routineData.products.map((p, i) => (
              <ProductCard key={i} product={p} index={i} />
            ))}
          </div>
        </motion.div>
      )}

      {/* Share / export */}
      <motion.div
        custom={4}
        variants={cardVariants}
        initial="hidden"
        animate="visible"
        className="flex gap-3 pb-4"
      >
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleShare}
          className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl border border-gray-200 text-gray-600 text-sm font-medium hover:bg-gray-50 transition-colors"
        >
          {copied ? (
            <><Check className="w-4 h-4 text-emerald-500" /> <span className="text-emerald-600">Copied!</span></>
          ) : (
            <><Share2 className="w-4 h-4" /> Share Report</>
          )}
        </motion.button>
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleDownload}
          className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl bg-gray-900 text-white text-sm font-semibold hover:bg-gray-800 transition-colors"
        >
          <Download className="w-4 h-4" /> Save Routine
        </motion.button>
      </motion.div>
    </div>
  );
}
